; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel=0 -mtriple=amdgcn -mcpu=gfx1250 < %s | FileCheck -check-prefixes=GFX1250,GFX1250-SDAG %s
; RUN: llc -global-isel=1 -mtriple=amdgcn -mcpu=gfx1250 < %s | FileCheck -check-prefixes=GFX1250,GFX1250-GISEL %s

declare <4 x i32> @llvm.amdgcn.tensor.desc.update.lane.v4i32(<4 x i32>, i32, i32 immarg)
declare <8 x i32> @llvm.amdgcn.tensor.desc.update.lane.v8i32(<8 x i32>, i32, i32 immarg)
declare void @llvm.amdgcn.tensor.load.to.lds(<4 x i32> %D0, <8 x i32> %D1, <4 x i32> %D2, <4 x i32> %D3, <8 x i32> %D4, i32 %cpol)

define amdgpu_ps void @desc_update_v4_lane1(<4 x i32> inreg %D0, <8 x i32> inreg %D1, <4 x i32> inreg %D2, <4 x i32> inreg %D3, i32 inreg %newLane) {
; GFX1250-LABEL: desc_update_v4_lane1:
; GFX1250:       ;=== Block: 6 cycles ===
; GFX1250-NEXT:  ; SALU:4 TDM:1
; GFX1250-NEXT:  ; Stall: 1 cycles (17%)
; GFX1250-NEXT:  ; RAW:1
; GFX1250-NEXT:  ; %bb.0:
; GFX1250-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_SCHED_MODE, 0, 5), 2
; GFX1250-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1 ; msbs: dst=0 src0=0 src1=0 src2=0
; GFX1250-NEXT:    s_mov_b32 s1, s20
; GFX1250-NEXT:    ;Sim: Stall:1 [RAW hazard]
; GFX1250-NEXT:    tensor_load_to_lds s[0:3], s[4:11], s[12:15], s[16:19]
; GFX1250-NEXT:    s_endpgm
  %u = call <4 x i32> @llvm.amdgcn.tensor.desc.update.lane.v4i32(<4 x i32> %D0, i32 %newLane, i32 1)
  call void @llvm.amdgcn.tensor.load.to.lds(<4 x i32> %u, <8 x i32> %D1, <4 x i32> %D2, <4 x i32> %D3, <8 x i32> zeroinitializer, i32 0)
  ret void
}

define amdgpu_ps void @desc_update_v4_lane2(<4 x i32> inreg %D0, <8 x i32> inreg %D1, <4 x i32> inreg %D2, <4 x i32> inreg %D3, i32 inreg %newLane) {
; GFX1250-LABEL: desc_update_v4_lane2:
; GFX1250:       ;=== Block: 6 cycles ===
; GFX1250-NEXT:  ; SALU:4 TDM:1
; GFX1250-NEXT:  ; Stall: 1 cycles (17%)
; GFX1250-NEXT:  ; RAW:1
; GFX1250-NEXT:  ; %bb.0:
; GFX1250-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_SCHED_MODE, 0, 5), 2
; GFX1250-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1 ; msbs: dst=0 src0=0 src1=0 src2=0
; GFX1250-NEXT:    s_mov_b32 s2, s20
; GFX1250-NEXT:    ;Sim: Stall:1 [RAW hazard]
; GFX1250-NEXT:    tensor_load_to_lds s[0:3], s[4:11], s[12:15], s[16:19]
; GFX1250-NEXT:    s_endpgm
  %u = call <4 x i32> @llvm.amdgcn.tensor.desc.update.lane.v4i32(<4 x i32> %D0, i32 %newLane, i32 2)
  call void @llvm.amdgcn.tensor.load.to.lds(<4 x i32> %u, <8 x i32> %D1, <4 x i32> %D2, <4 x i32> %D3, <8 x i32> zeroinitializer, i32 0)
  ret void
}

; The interesting pattern: chain three updates of lane 1 feeding four loads.
; Without the intrinsic, this would be 6x s_mov_b64 + 3x s_mov_b32 = 9 instrs.
; With it, it collapses to 3x s_mov_b32 on the shared SReg_128 tuple.
define amdgpu_ps void @desc_update_v4_chain(<4 x i32> inreg %D0, <8 x i32> inreg %D1, <4 x i32> inreg %D2, <4 x i32> inreg %D3, i32 inreg %v1, i32 inreg %v2, i32 inreg %v3) {
; GFX1250-LABEL: desc_update_v4_chain:
; GFX1250:       ;=== Block: 13 cycles ===
; GFX1250-NEXT:  ; SALU:6 TDM:4
; GFX1250-NEXT:  ; Stall: 3 cycles (23%)
; GFX1250-NEXT:  ; RAW:3
; GFX1250-NEXT:  ; %bb.0:
; GFX1250-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_SCHED_MODE, 0, 5), 2
; GFX1250-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1 ; msbs: dst=0 src0=0 src1=0 src2=0
; GFX1250-NEXT:    tensor_load_to_lds s[0:3], s[4:11], s[12:15], s[16:19]
; GFX1250-NEXT:    s_mov_b32 s1, s20
; GFX1250-NEXT:    ;Sim: Stall:1 [RAW hazard]
; GFX1250-NEXT:    tensor_load_to_lds s[0:3], s[4:11], s[12:15], s[16:19]
; GFX1250-NEXT:    s_mov_b32 s1, s21
; GFX1250-NEXT:    ;Sim: Stall:1 [RAW hazard]
; GFX1250-NEXT:    tensor_load_to_lds s[0:3], s[4:11], s[12:15], s[16:19]
; GFX1250-NEXT:    s_mov_b32 s1, s22
; GFX1250-NEXT:    ;Sim: Stall:1 [RAW hazard]
; GFX1250-NEXT:    tensor_load_to_lds s[0:3], s[4:11], s[12:15], s[16:19]
; GFX1250-NEXT:    s_endpgm
  call void @llvm.amdgcn.tensor.load.to.lds(<4 x i32> %D0, <8 x i32> %D1, <4 x i32> %D2, <4 x i32> %D3, <8 x i32> zeroinitializer, i32 0)
  %u1 = call <4 x i32> @llvm.amdgcn.tensor.desc.update.lane.v4i32(<4 x i32> %D0, i32 %v1, i32 1)
  call void @llvm.amdgcn.tensor.load.to.lds(<4 x i32> %u1, <8 x i32> %D1, <4 x i32> %D2, <4 x i32> %D3, <8 x i32> zeroinitializer, i32 0)
  %u2 = call <4 x i32> @llvm.amdgcn.tensor.desc.update.lane.v4i32(<4 x i32> %u1, i32 %v2, i32 1)
  call void @llvm.amdgcn.tensor.load.to.lds(<4 x i32> %u2, <8 x i32> %D1, <4 x i32> %D2, <4 x i32> %D3, <8 x i32> zeroinitializer, i32 0)
  %u3 = call <4 x i32> @llvm.amdgcn.tensor.desc.update.lane.v4i32(<4 x i32> %u2, i32 %v3, i32 1)
  call void @llvm.amdgcn.tensor.load.to.lds(<4 x i32> %u3, <8 x i32> %D1, <4 x i32> %D2, <4 x i32> %D3, <8 x i32> zeroinitializer, i32 0)
  ret void
}

define amdgpu_ps void @desc_update_v8_lane3(<4 x i32> inreg %D0, <8 x i32> inreg %D1, <4 x i32> inreg %D2, <4 x i32> inreg %D3, i32 inreg %newLane) {
; GFX1250-LABEL: desc_update_v8_lane3:
; GFX1250:       ;=== Block: 6 cycles ===
; GFX1250-NEXT:  ; SALU:4 TDM:1
; GFX1250-NEXT:  ; Stall: 1 cycles (17%)
; GFX1250-NEXT:  ; RAW:1
; GFX1250-NEXT:  ; %bb.0:
; GFX1250-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_SCHED_MODE, 0, 5), 2
; GFX1250-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1 ; msbs: dst=0 src0=0 src1=0 src2=0
; GFX1250-NEXT:    s_mov_b32 s7, s20
; GFX1250-NEXT:    ;Sim: Stall:1 [RAW hazard]
; GFX1250-NEXT:    tensor_load_to_lds s[0:3], s[4:11], s[12:15], s[16:19]
; GFX1250-NEXT:    s_endpgm
  %u = call <8 x i32> @llvm.amdgcn.tensor.desc.update.lane.v8i32(<8 x i32> %D1, i32 %newLane, i32 3)
  call void @llvm.amdgcn.tensor.load.to.lds(<4 x i32> %D0, <8 x i32> %u, <4 x i32> %D2, <4 x i32> %D3, <8 x i32> zeroinitializer, i32 0)
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; GFX1250-GISEL: {{.*}}
; GFX1250-SDAG: {{.*}}
